Repository verji/matrix-react-sdk, pull requests merged in 2024-05, with the labels that each got.

#30 Implement CustomComponent Lifecycles hooks Part 1
  src/components/structures/LoggedInView.tsx
  src/components/structures/RoomView.tsx
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/dialogs/SpaceSettingsDialog.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/spaces/SpacePanel.tsx
  test/components/structures/LoggedInView-test.tsx
  test/components/structures/RoomView-test.tsx
  test/components/views/dialogs/RoomSettingsDialog-test.tsx
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/components/views/spaces/SpacePanel-test.tsx
Labels: T-Enhancement, T-Task

#36 Eik/UI features account div1
  src/components/views/dialogs/devtools/BaseTool.tsx
  src/components/views/directory/NetworkDropdown.tsx
  src/components/views/elements/PowerSelector.tsx
  src/components/views/elements/SearchWarning.tsx
  src/components/views/settings/ThemeChoicePanel.tsx
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  src/settings/Settings.tsx
  src/settings/UIFeature.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/views/elements/PowerSelector-test.tsx
  test/components/views/settings/ThemeChoicePanel-test.tsx
  test/components/views/settings/tabs/user/VoiceUserSettingsTab-test.tsx
  test/utils/oidc/authorize-test.ts
Labels: T-Enhancement, T-Task

#38 Rm/1911 new div6
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/settings/Settings.tsx
  src/settings/UIFeature.ts
  src/toasts/BulkUnverifiedSessionsToast.ts
  test/DeviceListener-test.ts
  test/components/views/settings/tabs/user/PreferencesUserSettingsTab-test.tsx
Labels: T-Task

#41 Rm/1917 div8
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/settings/Settings.tsx
  src/settings/UIFeature.ts
  test/components/views/settings/tabs/user/PreferencesUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
Labels: T-Task

#40 Eik/UI features account div1
  package.json
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
  src/settings/Settings.tsx
  src/settings/UIFeature.ts
  test/components/views/context_menus/RoomContextMenu-test.tsx
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/components/views/dialogs/__snapshots__/UserSettingsDialog-test.tsx.snap
  test/components/views/rooms/RoomKnocksBar-test.tsx
  test/components/views/settings/tabs/room/PeopleRoomSettingsTab-test.tsx
  test/components/views/settings/tabs/user/SidebarUserSettingsTab-test.tsx
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  yarn.lock
Labels: T-Enhancement, T-Deprecation
