Repository verji/matrix-react-sdk, pull requests merged in 2024-08, with the labels that each got.

#69 Eik/reactivate securitytab
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/i18n/strings/nb_NO.json
  src/settings/Settings.tsx
  src/settings/UIFeature.ts
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/components/views/dialogs/__snapshots__/UserSettingsDialog-test.tsx.snap
Labels: T-Enhancement, T-Task

#80 Rm/1995 invite dialog
  res/css/_components.pcss
  src/i18n/strings/en_EN.json
  src/i18n/strings/nb_NO.json
Labels: T-Task

#81 fixing tests part one 1
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/messages/ReactionsRowButtonTooltip.tsx
  test/components/structures/ReactionsRowButtonTooltip-test.tsx
  test/components/structures/__snapshots__/ReactionsRowButtonTooltip-test.tsx.snap
  test/components/views/dialogs/InviteDialog-test.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/rooms/RoomList-test.tsx
  test/components/views/settings/__snapshots__/PowerLevelSelector-test.tsx.snap
  test/components/views/settings/notifications/__snapshots__/Notifications2-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/SpaceTreeLevel-test.tsx.snap
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
Labels: T-Task

#84 Eik/hide labs and sharedinvites
  res/css/structures/_RightPanel.pcss
  src/components/structures/scripts/freshworks.js
  src/components/views/dialogs/BugReportDialog.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/misc_header/MiscButton.tsx
  src/components/views/misc_header/MiscHeaderButtons.tsx
  src/components/views/right_panel/LegacyRoomHeaderButtons.tsx
  src/components/views/rooms/EntityTile.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/MemberTile.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  src/i18n/strings/nb_NO.json
  src/settings/Settings.tsx
  src/settings/UIFeature.ts
  src/stores/right-panel/RightPanelStorePhases.ts
  test/components/views/dialogs/InviteDialog-test.tsx
  test/components/views/dialogs/__snapshots__/InviteDialog-test.tsx.snap
  test/components/views/rooms/__snapshots__/MemberTile-test.tsx.snap
Labels: T-Enhancement, T-Task

#83 Fixing Tests Part 2
  .github/workflows/static_analysis.yaml
  .github/workflows/tests.yml
  scripts/ci/layered.sh
  test/MatrixClientPeg-test.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/__snapshots__/MatrixChat-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
Labels: T-Task

#86 Eik/hide labs and sharedinvites
  .eslintignore
  res/css/structures/_RightPanel.pcss
  src/components/structures/scripts/freshworks.js
  src/components/views/dialogs/BugReportDialog.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/misc_header/MiscButton.tsx
  src/components/views/misc_header/MiscHeaderButtons.tsx
  src/components/views/right_panel/LegacyRoomHeaderButtons.tsx
  src/components/views/rooms/EntityTile.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/MemberTile.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  src/i18n/strings/nb_NO.json
  src/settings/Settings.tsx
  src/settings/UIFeature.ts
  src/stores/right-panel/RightPanelStorePhases.ts
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/dialogs/InviteDialog-test.tsx
  test/components/views/dialogs/__snapshots__/InviteDialog-test.tsx.snap
  test/components/views/right_panel/__snapshots__/LegacyRoomHeaderButtons-test.tsx.snap
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/rooms/__snapshots__/MemberTile-test.tsx.snap
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
  test/components/views/settings/tabs/user/HelpUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/LabsUserSettingsTab-test.tsx.snap
  test/stores/widgets/StopGapWidget-test.ts
Labels: T-Enhancement, T-Task

#89 Eik/hide labs and sharedinvites
  src/settings/UIFeature.ts
Labels: T-Enhancement, T-Deprecation

#92 Jts/1998 invite to space
  src/components/views/rooms/RoomList.tsx
  src/settings/Settings.tsx
  src/settings/UIFeature.ts
  test/components/views/rooms/RoomList-test.tsx
Labels: T-Task

#93 Eik/hide labs and sharedinvites
  src/components/views/right_panel/LegacyRoomHeaderButtons.tsx
  test/components/views/right_panel/__snapshots__/LegacyRoomHeaderButtons-test.tsx.snap
  yarn.lock
Labels: T-Enhancement, T-Task
